valor = 2       #(DEFINCIÓN VARIABLE PARA EJEMPLO)

#UNA SUBRUTINA ES SIMILAR A UN MÉTODO DE JAVA.
#PARA CREAR UNA SUBRUTINA, UTILIZAMOS LA PALABRA 'DEF' SEGUIDA POR EL NOMBRE DE LA SUBRUTINA
#Y POR LOS PARÁMETROS (SI LOS HAY) ENTRE PARÉNTESIS. FINALIZAMOS CON :
#ASÍ PUES, QUEDARÍA ALGO ASÍ:

def Subrutina (valor):
    #INDENTADO, ESCRIBIREMOS EL CÓDIGO QUE QUEREMOS EJECUTAR.
    print ("El doble del valor es =",valor*2)
    boolean = (valor*2>5)
    #AL IGUAL QUE EN JAVA, PODEMOS HACER QUE DEVUELVA UN VALOR.
    return print (boolean)

Subrutina(valor)        #PARA LLAMAR A LA SUBRUTINA, ESCRIBIMOS SU NOMBRE
            #ENTRE PARÉNTESIS INTRODUCIMOS EL PARÁMETRO
            #EL NOMBRE DEL PARÁMETRO NO TIENE POR QUÉ COINCIDIR DENTRO Y FUERA DE LA SUBRUTINA